spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

  jpa:
    show-sql: true

  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
